spring:
    application:
        name: readinglist

rocketmq:
  namesrvAddr: 192.168.172.3:9876
  producerGroupName: producerGroup
  consumerGroupName: consumerGroup
  producerInstanceName: producerInstanceName
  consumerInstanceName: consumerInstanceName
  producerTranInstanceName: producerTranInstanceName
  consumerBatchMaxSize: 1
  consumerBroadcasting: false
  subscribe[0]: TopicTest1:TagA
  enableHisConsumer: false
  enableOrderConsumer: false
