spring:
    application:
        name: readinglist
    redis:
        host: 192.168.172.3
        port: 6379
        password:
        timeout: 10000
        pool:
        max-idle: 20
        min-idle: 5
        max-active: 20
        max-wait: 2
    data:
        elasticsearch:
            cluster-nodes: 60.205.151.183:19300
            cluster-name: gzc_es_test